---
deployment:
  tasks:
    - export DEPLOYPATH=/home/atlarrik/atlant28.atlantlogistics.com/
    - /bin/rsync -rltDvz --exclude=".git" --exclude=".htaccess" ./ $DEPLOYPATH
    - /bin/chmod 755 $DEPLOYPATH
    - /bin/chmod 644 $DEPLOYPATH/.htaccess